name: build
on:
  push:
    branches-ignore:
      - main
    paths:
      - .github/workflows/build.yml
      - docker/Dockerfile.helmku
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}/helmku
  CONTEXT: ${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}
  CONTEXT_SUB_PATH: docker
  DOCKERFILE: Dockerfile.helmku
  ALPINE_VERSION: 3.20.2
  KUBE_VERSION: 1.29.6
  HELM_VERSION: 3.15.3

  # used by kaniko for git clone `context`
  GIT_USERNAME: ${{ github.actor }}
  GIT_PASSWORD: ${{ github.token }}
  RUNNERS_VERSION: 0.0.1

  # trigger workflow
  RUNNING_NUMBER: 20241213-1454
jobs:
  helmku:
    runs-on: ubuntu-latest
    container: gcr.io/kaniko-project/executor:v1.23.2-debug
    permissions:
      contents: read
      packages: write
      id-token: write
    timeout-minutes: 60
    steps:
      - name: Build and push Docker image
        id: push
        run: |
          echo image: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{env.RUNNERS_VERSION}}
          echo "{\"auths\":{\"$REGISTRY\":{\"auth\":\"$(echo -n ${{github.actor}}:${{github.token}} | base64)\"}}}" > /kaniko/.docker/config.json
          /kaniko/executor \
            --context "${{ env.CONTEXT }}" \
            --context-sub-path "${{env.CONTEXT_SUB_PATH}}" \
            --dockerfile "${{env.DOCKERFILE}}" \
            --destination "${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{env.RUNNERS_VERSION}}" \
            --digest-file digest.txt \
            --build-arg ALPINE_VERSION=${{env.ALPINE_VERSION}} \
            --build-arg KUBE_VERSION=${{env.KUBE_VERSION}} \
            --build-arg HELM_VERSION=${{env.HELM_VERSION}}
          echo digest=`cat digest.txt` >> $GITHUB_OUTPUT
          echo digest: `cat digest.txt`
      # - name: Attest Build Provenance
      #   uses: actions/attest-build-provenance@2.1.0
      #   with:
      #     subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     push-to-registry: true